#!/bin/sh
#
# Copyright 2010 Thomas Eastman
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Download KEGG data files.
#
# This program assumes that the root of the retrieved KEGG directory
# hierarchy should be the current working directory.
#
# This program downloads the non organism-specific files required by
# the Kegg.pm interface.  The other files are generated by the program
# update_pathways.py through the KEGG web services.
#

wget --force-directories --no-host-directories --cut-dirs=2 --progress=dot --wait=3 --input-file=- <<EOF
ftp://ftp.genome.jp/pub/kegg/pathway/map_title.tab
ftp://ftp.genome.jp/pub/kegg/ligand/compound/compound*
ftp://ftp.genome.jp/pub/kegg/ligand/compound/merged_compound.lst
ftp://ftp.genome.jp/pub/kegg/ligand/reaction/reaction*
ftp://ftp.genome.jp/pub/kegg/ligand/rpair/rpair
ftp://ftp.genome.jp/pub/kegg/ligand/enzyme/enzyme
ftp://ftp.genome.jp/pub/kegg/ligand/glycan/glycan
ftp://ftp.genome.jp/pub/kegg/genes/ko
ftp://ftp.genome.jp/pub/kegg/brite/br/br08901.keg
EOF



# these files are no longer proivided by KEGG via FTP:
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/hsa/*.cpd
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/hsa/*.rn
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/hsa/*.orth
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/cel/*.cpd
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/cel/*.rn
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/cel/*.orth
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/ssc/*.cpd
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/ssc/*.rn
# ftp://ftp.genome.jp/pub/kegg/pathway/organisms/ssc/*.orth
# ftp://ftp.genome.jp/pub/kegg/pathway/map/map*.cpd
# ftp://ftp.genome.jp/pub/kegg/pathway/map/map*.rn
# ftp://ftp.genome.jp/pub/kegg/pathway/map/map*.orth
